### ISSUE TITLE
Displaying wrong version after installing Zenbership v115.Displayed version is v111.

### ISSUE THREAD

**Issue by prbt2016** [castlamp/zenbership#127]
Hi,
I downloaded Zenbership version 115 from here 
https://www.zenbership.com/Download .However after manual installation i am getting version displayed as v111 in the footer and in the admin panel  .
Also in the 'ppSD_options'  table the value of 'id'   i.e 'current_version' is 111.Can you please resolve the issue.
Awaiting your kind reply  .

**Comment by NA7KR** [comment]
Same here v111

**Comment by NA7KR** [comment]
Found Version is in Database  ppSD_options
UPDATE `TABLENAME`.`ppSD_options` SET `value`='115' WHERE  `id`='current_version';
Will need to change TABLNAME to match yours.

**Comment by steviobee** [comment]
Does the database need updating or where can I check I actually have the latest version?

**Comment by steviobee** [comment]
Can someone confirm if I have 115 version? Can you tell by looking? I'm happy to edit the ppSD_options but:
a) don't want to break anything
b) would rather check that I actually have the correct version and am not just changing it to make it look right in the ppSD_options

https://members.vespaclubsydney.com.au

**Comment by dameon6** [comment]
Compare the v115 .htaccess file on this branch to the one in your folder. They should match.

**Comment by steviobee** [comment]
Ah, it appears they do not? The one I have in my folder is 65 lines in total, the one in this branch appears to be 87 in total? 
If I were to try an upgrade, apart from the fear of it all falling over is that the instructions on upgrade page of Zenbership  say to not copy the .htaccess file?

**Comment by dameon6** [comment]
Thats odd because mine matches, of course mine says 86 lines because I don't have the unneeded space at the top of the file.  Go through it line by line and see what the differences are?  Sometimes web servers won't let you update through upload the .htaccess file because its protected, you'd actually have to edit it through Cpanel instead.    I will try to check some other files.

**Comment by steviobee** [comment]
There is an issue with mine then, I only have 56-58 (3) Main rewrites. As opposed to 56-74 in newly downloaded file.  Can I just edit it in cPanel to update it?

I was sure I uploaded the latest version from the main website zenbership.com, unless it changed in the last week or so?

**Comment by dameon6** [comment]
I would just edit it and add the missing lines using cpanel, that should make it match up. I installed mine back in October.  htaccess can be weird due to the protections its provided from the hosting provider.

**Comment by steviobee** [comment]
I have updated the .htaccess to add the missing lines, this makes me wonder why we are told not to overwrite while going through update procedure as described on the Zenbership website?

**Comment by dameon6** [comment]
It depends on your hosting environment, overwriting it can eliminate lines that were added by your provider that are required in order for the site to work properly, such as apache directives.  This is why they normally tell you to edit it instead of overwriting.  I run my own server so I just overwrite.

**Comment by jbelelieu** [comment]
The initial version is hard coded into the setup/process.php file. It's not ideal but it's how it works for now. I updated and bumped that in a recent commit.
